### ISSUE TITLE
Logic typo on example in this readme

### ISSUE THREAD

**Issue by campbelllssoup** [learn-co-curriculum/fewpjs_arrow_function_shorthand#4]
1 const nums = [1,2,3];
2 const squares = nums.map(x => x ** 2); //=> [2,4,6]
3 const doubles = nums.map(x => x * 2); //=> [1,4,9]

So it is displayed in the above way on the learn.co page for the lab - BUT instead of the part to the right of the variable assignment on line two ' //=> [2,4,6]' it needs to be '//=> [1,4,9]'. And vice versa for line 3.

**Comment by maxwellbenton** [comment]
Hi @campbelllssoup,

Thank you for spotting this and providing feedback. We've switched the comments to correctly display the outputs beside each map.

**Comment by campbelllssoup** [comment]
Dear Maxwell,

    Anytime - I’m glad I could help.

    Best Regards,
        Matthew Campbell
